# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuzzWords',
            fields=[
                ('buzz_word', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CeleryTasksRetrying',
            fields=[
                ('task_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('uni_handle', models.CharField(max_length=128)),
                ('task_name', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=4096)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=4096)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('twitter_handle', models.CharField(default='', max_length=128)),
                ('last_refresh', models.DateTimeField()),
                ('description', models.CharField(default='', max_length=4096)),
                ('name', models.CharField(default='', max_length=128)),
                ('contacted', models.BooleanField(default=False)),
                ('contacted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStats',
            fields=[
                ('task_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_handle', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_refresh', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='graduate',
            name='following',
            field=models.ManyToManyField(to='follower_descriptions.University'),
        ),
        migrations.AddField(
            model_name='comment',
            name='graduate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follower_descriptions.Graduate'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
