# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_refresh', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UniFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follower_descriptions.Graduate')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_handle', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('last_refresh', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='unifollowers',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follower_descriptions.University'),
        ),
    ]
