# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='location',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
