# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0002_graduate_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='twitter_handle',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
