# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0002_graduate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
