# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0003_graduate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
