# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0004_auto_20160111_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='following',
            field=models.ManyToManyField(to='follower_descriptions.University'),
        ),
    ]
