# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0008_auto_20160312_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
