# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follower_descriptions', '0009_auto_20160312_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=4096)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follower_descriptions.Graduate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
