# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='twitter_handle',
            field=models.CharField(default='', max_length=128),
        ),
    ]
