# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0013_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStats',
            fields=[
                ('task_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='unifollowers',
            name='graduate',
        ),
        migrations.RemoveField(
            model_name='unifollowers',
            name='university',
        ),
        migrations.DeleteModel(
            name='UniFollowers',
        ),
    ]
