# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0014_auto_20160418_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTasksRetrying',
            fields=[
                ('task_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('uni_handle', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
