# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0015_buzzwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buzzwords',
            name='id',
        ),
        migrations.AddField(
            model_name='buzzwords',
            name='hits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buzzwords',
            name='buzz_word',
            field=models.CharField(default='', max_length=128, primary_key=True, serialize=False),
        ),
    ]
