# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0015_celerytasksretrying'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celerytasksretrying',
            old_name='date',
            new_name='created',
        ),
    ]
