# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0016_auto_20160523_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasksretrying',
            name='task_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
