# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0017_celerytasksretrying_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graduate',
            name='contacted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
