# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0016_auto_20160524_2137'),
        ('follower_descriptions', '0017_celerytasksretrying_task_name'),
    ]

    operations = [
    ]
