# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follower_descriptions', '0018_auto_20160524_2220'),
        ('follower_descriptions', '0019_auto_20160524_2259'),
    ]

    operations = [
    ]
